### ISSUE TITLE
scripts: bug: During deployment some calls ran out of gas on Boba

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#775] opened 2022-06-20 10:36 UTC
While running the deployment script some calls like `addCaller` ran out of gas pn Boba network. Calling them manually afterwards succeeded. 
We need to investigate why the gas limit was chosen so low. I can confirm that the successful call later was given a much higher gas limit.

**Comment by istankovic** [comment] 2022-07-05 13:27
Could not reproduce, closing.

**Closed by istankovic** 2022-07-05 13:27 UTC
Labels: bug, infrastructure :hammer:
