### ISSUE TITLE
Verify contracts on rollups

### ISSUE THREAD

**Issue by czepluch** [beamer-bridge/beamer#444] opened 2022-03-25 12:42 UTC
## Description
The current testnet contracts should be verified. It's possible to do so on both Boba and Metis testnets through http://sourcify.dev/. We should also incorporate automating this into our deployment script.

## Acceptance criteria
Contracts are verified on our supported testnets

**Comment by palango** [comment] 2022-03-30 08:37
Duplicate of #328

**Closed** 2022-03-30 08:36 UTC
