### ISSUE TITLE
Boba -> Optimism - Error "insufficient funds"

### ISSUE THREAD

**Issue by heifra** [beamer-bridge/beamer#971] opened 2022-08-25 12:02 UTC
#### System information

OS & Version: OSX
Browser & Version: Brave
Commit hash: when using checkout

#### Expected behavior
I enter a value of 1 USD (or 5 USD) in the transfer field. It should validate that I have sufficient funds to transfer (>8 USDC available on Boba). Works also for 1.00 or 5.00

#### Actual behavior
Get the error Isufficient funds

#### Steps to reproduce the behavior
Try to transfer this amount from Boba to Optimism in my environment?

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/5898071/186658915-7181679d-1e5d-4191-b0aa-4ad6b62e00eb.png">

**Comment by heifra** [comment] 2022-08-25 12:03
<img width="609" alt="image" src="https://user-images.githubusercontent.com/5898071/186659286-072509a8-dd64-4822-a672-da899b962399.png">

**Comment by heifra** [comment] 2022-08-25 13:33
As discussed with Fred two more infos. 
It happens only with Boba as source.
The error "insufficient funds" appears already when typing "5". 
The error in the console happens when then proceeding to "5."

**Comment by GabrielBuragev** [comment] 2022-08-25 13:42
@heifra Thank you for reporting this issue and for providing these details.

I tried reproducing it on Brave but was not able to. 
Can you please check if you have multiple addresses in your metamask connected to the app? If so can you try disconnecting all of them and connect only the `0x139...a6D7`. After that try filling up the inputs.

If the only address connected to the app is this one, then the problem might be in something else and i will need to further debug.
Would need your input so i can continue debugging.

Btw. the "error" related to "5." is just a warning from the browser since "5." is not a valid number format. So that's nothing related to the "Insufficient funds" error.

**Comment by heifra** [comment] 2022-08-31 13:39
Checked it now. The error is not reproducable anymore. Works fine now

**Comment by heifra** [comment] 2022-08-31 13:39
(Without reconnecting)

**Comment by GabrielBuragev** [comment] 2022-08-31 13:44
This issue was most likely related to issue #964. 
Due to the wrong user balance calculation for tokens with less then 18 decimals this error started showing up as the input validation was checking and validating against the incorrect user balance amount.
Since the user balance calculation was fixed with #959 this error stopped showing up therefore closing this issue as resolved.

**Closed by GabrielBuragev** 2022-08-31 13:44 UTC
Labels: bug, frontend :lollipop:
